export default function PDFReport({ projectName, reportData, budget, totalSpent }) {
  const generatePDF = () => {
    // Create a hidden iframe or open a new window with HTML content
    const printWindow = window.open('', '_blank');
    
    // Build the HTML report
    const htmlContent = `
      <!DOCTYPE html>
      <html>
      <head>
        <title>${projectName} - Cost Report</title>
        <style>
          body { font-family: Arial, sans-serif; margin: 40px; }
          h1 { color: #2c3e50; }
          table { width: 100%; border-collapse: collapse; margin-top: 20px; }
          th, td { border: 1px solid #ddd; padding: 8px; text-align: left; }
          th { background-color: #f2f2f2; }
          .summary { margin: 20px 0; background: #f9f9f9; padding: 10px; }
        </style>
      </head>
      <body>
        <h1>Construction Project Tracker – Cost Report</h1>
        <h2>Project: ${projectName}</h2>
        <div class="summary">
          <p><strong>Budget:</strong> ${budget.toLocaleString()} RWF</p>
          <p><strong>Total Spent:</strong> ${totalSpent.toLocaleString()} RWF</p>
          <p><strong>Remaining:</strong> ${(budget - totalSpent).toLocaleString()} RWF</p>
        </div>
        <table>
          <thead>
            <tr><th>Material</th><th>Quantity</th><th>Unit Price (RWF)</th><th>Total Cost (RWF)</th></tr>
          </thead>
          <tbody>
            ${reportData.map(item => `
              <tr>
                <td>${item.MaterialName}</td>
                <td>${item.TotalQuantity}</td>
                <td>${item.UnitPrice.toLocaleString()}</td>
                <td>${item.TotalCost.toLocaleString()}</td>
              </tr>
            `).join('')}
          </tbody>
        </table>
        <p style="margin-top: 30px;"><em>Generated by SolidRock Construction Tracker</em></p>
      </body>
      </html>
    `;
    
    printWindow.document.write(htmlContent);
    printWindow.document.close();
    printWindow.print();  // Opens print dialog – user can "Save as PDF"
  };

  return (
    <button onClick={generatePDF} className="bg-red-600 text-white p-2 rounded">
      Download PDF Report (Print)
    </button>
  );
}